### ISSUE TITLE
sar-datetime-picker-input组件怎么配置输出变量是 2024-01-28 12:44:29 的格式啊？

### ISSUE THREAD

**Issue by chergn** [sutras/sard-uniapp#10]
![image](https://github.com/sutras/sard-uniapp/assets/43592730/c2a0c2a1-d3e5-468a-9346-71804ed5bcfa)

**Comment by sutras** [comment]
sard-uniapp中涉及到日期的组件，都是通过Date对象绑定的，而不是字符串，因此最终发送到服务器前需要使用moment或者dayjs等库将其字符串格式化。
