### ISSUE TITLE
使用sar-stepper报错

### ISSUE THREAD

**Issue by chergn** [sutras/sard-uniapp#11]
![image](https://github.com/sutras/sard-uniapp/assets/43592730/5b89ae3b-93c9-444c-86cf-cb8e2fcf59ef)

**Comment by sutras** [comment]
sass 的 string.split() 方法需要Dart Sass 1.57.0版本之后才能使用，而HBuilderX安装的dart-sass版本为1.43.4，因此会报错。
建议使用sard-uniapp组件库的项目通过命令行的方式创建，而不是HBuilderX：
```bash
npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project
```

**Comment by zhaoyingsen123** [comment]
已经创建了项目 改如何升级版本

**Comment by sutras** [comment]
可以参考uniapp官网升级教程：
https://uniapp.dcloud.net.cn/quickstart-cli.html#cliversion

**Comment by zhaoyingsen123** [comment]
如果我想只升级Dart Sass的版本呢

**Comment by zhaoyingsen123** [comment]
谢谢，上面的问题解决了
