### ISSUE TITLE
sar-upload 组件报错

### ISSUE THREAD

**Issue by chergn** [sutras/sard-uniapp#12]
![image](https://github.com/sutras/sard-uniapp/assets/43592730/d3e46ba3-7814-43f1-8d43-7f57cd72e1d5)

**Comment by sutras** [comment]
sass 的 string.split() 方法需要Dart Sass 1.57.0版本之后才能使用，而HBuilderX安装的dart-sass版本为1.43.4，因此会报错。
建议使用sard-uniapp组件库的项目通过命令行的方式创建，而不是HBuilderX：
```bash
npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project
```

**Comment by chergn** [comment]
> sass 的 string.split() 方法需要Dart Sass 1.57.0版本之后才能使用，而HBuilderX安装的dart-sass版本为1.43.4，因此会报错。 建议使用sard-uniapp组件库的项目通过命令行的方式创建，而不是HBuilderX：
> 
> ```shell
> npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project
> ```

能能不能降组件库的sass的版本啊，或者使用scss。这样兼容更多开发者嘛
