### ISSUE TITLE
bug: button 自定义 color 失效？

### ISSUE THREAD

**Issue by izrio** [sutras/sard-uniapp#14]
<sar-button background="#f0f2f5" color="#9195A2">按钮</sar-button>
<img width="1014" alt="image" src="https://github.com/sutras/sard-uniapp/assets/46107383/fe358d24-d12e-45bc-94f0-dd425001fc5b">

**Comment by izrio** [comment]
` <sar-button background="#f0f2f5" color="#9195A2">
        按钮
      </sar-button>`

**Comment by sutras** [comment]
可能是微信开发者工具热更新失效，试一下点击微信开发者工具上面的“编译”试试？
