### ISSUE TITLE
微信小程序load-more配合PullDownRefresh组件一起使用下拉时偶发性无法下拉

### ISSUE THREAD

**Issue by izrio** [sutras/sard-uniapp#18]
微信小程序load-more配合PullDownRefresh组件一起使用下拉时偶发性无法下拉
演示小程序可复现，加载完全部数据后，偶发性无法下拉刷新

**Comment by sutras** [comment]
下拉刷新组件需在容器的scrollTop为0、且向下滑动手指时触发。出现偶发性无法下拉情况，可能scrollTop不为0，或者滑动的角度水平大于垂直。

**Comment by sutras** [comment]
问题已修复，接口有所改动，具体可以查看文档：

https://sutras.github.io/sard-uniapp-docs/#/components/pull-down-refresh
