### ISSUE TITLE
如果能接入unocss+iconify就好了

### ISSUE THREAD

**Issue by chergn** [sutras/sard-uniapp#2]
1. unocss量子化样式引擎能解放双手写css。
2. iconify动态图标，重点是集成库，谁家的图标都能用

**Comment by haobarry** [comment]
直接可以用吧  它的组件会透传class 么

**Comment by sutras** [comment]
unocss、tailwindcss或windicss这些原子化的css解决方案，都是通过在元素上添加全局类名实现样式设置的。

sard-uniapp的组件都设置了`virtualHost: true`，即自定义元素外层是虚拟的节点，class和style等外部属性默认不会透传到组件内部的元素上，你可以通过view包裹sard-uniapp组件，再将class或style添加到view上；

或者可以使用`mergeVirtualHostAttributes`合并组件虚拟节点外层属性，使其更加接近Vue组件的表现。

**Comment by sutras** [comment]
sard-uniapp不会限制使用图标的方式，你可以使用Iconify或者iconfont或其他的图标库。
在小程序中使用svg图标会有一定的限制。

**Comment by aliyoung** [comment]
> sard-uniapp不会限制使用图标的方式，你可以使用Iconify或者iconfont或其他的图标库。 在小程序中使用svg图标会有一定的限制。

可以举个iconify的示例吗？
