### ISSUE TITLE
dateTimepicker 再次打开选中数据不正确

### ISSUE THREAD

**Issue by izrio** [sutras/sard-uniapp#20]

**Comment by izrio** [comment]
![image](https://github.com/sutras/sard-uniapp/assets/46107383/6923314d-ad09-4ae7-aac1-bc9731e6bf61)

假如 v-model为2024-04-30，第一次打开弹窗选项正确，然后更改为2024-04-20后，关闭弹窗，实际没有触发确定更改v-model值，再次打开显示2024-04-20， 实际应该显示2024-04-30

**Comment by sutras** [comment]
能否提供复现问题的代码片段？
