### ISSUE TITLE
那个gitee的网站挂了

### ISSUE THREAD

**Issue by haobarry** [sutras/sard-uniapp#21]

**Comment by sutras** [comment]
是的，最近gitee pages服务除了问题，已有很多用户提了issues，静待官方修复:
https://gitee.com/oschina/git-osc/issues

可以先访问部署到github上的文档：
https://sutras.github.io/sard-uniapp-docs/#/guide/intro

**Comment by zhoupengyu2019** [comment]
> 是的，最近gitee pages服务除了问题，已有很多用户提了issues，静待官方修复: https://gitee.com/oschina/git-osc/issues
> 
> 可以先访问部署到github上的文档： https://sutras.github.io/sard-uniapp-docs/#/guide/intro

有交流群吗？ 这个组件库会一直维护吧 ？

**Comment by sutras** [comment]
暂无创建交流群的计划，有问题可以在github上交流。
这个组件库会一直维护。

**Comment by modushanghai** [comment]
> 暂无创建交流群的计划，有问题可以在github上交流。 这个组件库会一直维护。

收到 ！  非常不错的组件库 ， 想用一些商业化项目  ， 希望一直更新 ~

**Comment by modushanghai** [comment]
z在问一下 ，  现在支持微信小程序skyline渲染吗？

**Comment by sutras** [comment]
目前暂不支持微信小程序skyline渲染，以后会考虑兼容，但具体时间未定。

**Comment by chergn** [comment]
真是，gitee太不稳定了。我的博客还写在简历里，结果崩了。后来放到GitHub pages了

**Comment by elarbor** [comment]
> 有交流群吗？ 这个组件库会一直维护吧 ？

有[discussions](https://github.com/sutras/sard-uniapp/discussions)啊

**Comment by elarbor** [comment]
> > 是的，最近gitee pages服务除了问题，已有很多用户提了issues，静待官方修复: https://gitee.com/oschina/git-osc/issues
> > 可以先访问部署到github上的文档： https://sutras.github.io/sard-uniapp-docs/#/guide/intro
> 
> 有交流群吗？ 这个组件库会一直维护吧 ？

有[discussions](https://github.com/sutras/sard-uniapp/discussions)啊
