### ISSUE TITLE
dialog/toast 打开异常

### ISSUE THREAD

**Issue by korio3326** [sutras/sard-uniapp#24]
dialog/toast 页面首次渲染使用正常，跳转到其他页面后，再返回使用dialog/toast的页面，弹出失效，点击弹出无反应

**Comment by korio3326** [comment]
微信小程序异常

**Comment by korio3326** [comment]
<img width="563" alt="image" src="https://github.com/sutras/sard-uniapp/assets/169863088/716cd423-11eb-4027-826d-08c56d859ffc">
这段代码是否存在问题，在微信小程序中跳转到其他页面触发UnMounted删除了id，当返回页面再次触发dialog，导致id找不到，弹窗打开不了

**Comment by sutras** [comment]
最新版已修复此问题。
