### ISSUE TITLE
有没有交流群？

### ISSUE THREAD

**Issue by TAYUN** [sutras/sard-uniapp#25]
有交流群一起交流吗？

**Comment by sutras** [comment]
暂无创建交流群的计划，有问题可以在github上交流。

**Comment by chergn** [comment]
> 暂无创建交流群的计划，有问题可以在github上交流。

可以开通Discussions 模块
![image](https://github.com/user-attachments/assets/7bf2e44a-0f07-408f-b5fe-38fdb69cc005)
![image](https://github.com/user-attachments/assets/5aa8d04c-432e-411b-bc78-f378711a19aa)

**Comment by elarbor** [comment]
有[discussions](https://github.com/sutras/sard-uniapp/discussions)啊
