### ISSUE TITLE
checkbox 禁用失效

### ISSUE THREAD

**Issue by izrio** [sutras/sard-uniapp#27]
<img width="563" alt="image" src="https://github.com/sutras/sard-uniapp/assets/46107383/de8f6a1c-7b02-48e7-9fba-70dae3cd6767">

<img width="383" alt="image" src="https://github.com/sutras/sard-uniapp/assets/46107383/b0b19b00-586d-420f-bebc-9c3e024f8120">

**Comment by sutras** [comment]
最新版已修复
