### ISSUE TITLE
样式穿透不生效啊

### ISSUE THREAD

**Issue by chergn** [sutras/sard-uniapp#3]
我也想要这样的效果：
![image](https://github.com/sutras/sard-uniapp/assets/43592730/ef92034e-2b9b-411a-b4a5-e865b09e0167)

于是我先随便给个颜色看看：
![image](https://github.com/sutras/sard-uniapp/assets/43592730/b89fd487-c926-4265-b671-7385ee7f3a1f)
 穿透不生效

**Comment by sutras** [comment]
我这边经过测试可以生效，或许你在HBuilderX重新运行到小程序试试。
