### ISSUE TITLE
PickerInput 能否支持多选？

### ISSUE THREAD

**Issue by izrio** [sutras/sard-uniapp#31]

**Comment by sutras** [comment]
PickerInput 组合了Picker、弹出框、输入框组件，其中Picker组件支持的属性PickerInput都支持。
你所说的多选应该指的是多列选择，columns 属性如果是一个二维数组会显示为多列。

具体文档可以查看：
https://sutras.github.io/sard-uniapp-docs/#/components/picker#PickerProps

**Comment by izrio** [comment]
![image](https://github.com/sutras/sard-uniapp/assets/46107383/dfb9be20-b65b-4347-853c-9a4e29835f37)
我所表达的是图上这种类型，相当于select的multiple，通过PopoutInput可以自己实现。能内置当然更好啦

**Comment by sutras** [comment]
明白，后期考虑新增。
