### ISSUE TITLE
Component `keyboard` has a incompatible emit between doc and source

### ISSUE THREAD

**Issue by Dedicatus546** [sutras/sard-uniapp#34]
in docs:
![image](https://github.com/user-attachments/assets/226b3ff2-00c2-4653-8f33-69bfc5062a4e)

in source:
![image](https://github.com/user-attachments/assets/40ab6b3a-3e94-4a68-9863-d6ffb01f054c)

**Comment by chergn** [comment]
挺不错的移动端组件库，就是知道的人太少

**Comment by Dedicatus546** [comment]
pr #35
