### ISSUE TITLE
解决通过HBuilderX创建的项目引入sar-uniapp，出现的sass 的 string.split()报错问题

### ISSUE THREAD

**Issue by Hoinor** [sutras/sard-uniapp#44]
1、打开HBuilderX安装目录
2、在plugins目录找到compile-dart-sass文件夹，点进去
3、编辑package.json，把 sass版本调成到1.57.0以上
4、在这个目录下，重新npm install 
5、重新运行项目

**Comment by chergn** [comment]
哦哦，就是`sass`的版本问题
