### ISSUE TITLE
sar-count-down 组件bug？

### ISSUE THREAD

**Issue by izrio** [sutras/sard-uniapp#46]
sar-count-down 在当前页面设置2分钟倒计时，然后退出当前页面，2分钟后依然触发finish

**Comment by sutras** [comment]
v1.6.1已修复

**Comment by chergn** [comment]
其实咱们的组件库也不用内置图标，主要是太少不够用。使用[unocss](https://icones.js.org/)+[iconify](https://icones.js.org/)的图标库就很方便。二十多万的图标总有适合自己的
![image](https://github.com/user-attachments/assets/50b84ade-78e2-4685-ab40-4cd215f904c4)
![image](https://github.com/user-attachments/assets/d1b33108-90c4-4c6d-9112-4cc0546b5764)
![image](https://github.com/user-attachments/assets/f3555ff4-b1dc-4b3f-93cb-ed9ef8f56a0f)

希望咱们的组件库能直接内置
