### ISSUE TITLE
sar-input的cursor属性设置无效。

### ISSUE THREAD

**Issue by G202liukaili** [sutras/sard-uniapp#47]
sar-input的cursor属性官方标注为：设定聚焦时的光标位置，但是在首次聚焦时，即使输入框中有值，光标位置仍然在第一位，如何让有值时光标聚焦在最后一位呢。

**Comment by sutras** [comment]
这是一个bug，在 v1.7.1 中已修复。
造成这个bug的原因是没有给 `cursor`、`selection-start` 和 `selection-end` 属性显式设置默认值。

**Comment by chergn** [comment]
能不能开通仓库的discussion模块啊，让大家可以讨论
