### ISSUE TITLE
 $list: string.split($str, ','); Failed to fetch dynamically imported module: 

### ISSUE THREAD

**Issue by qingtian-boy** [sutras/sard-uniapp#50]
![image](https://github.com/user-attachments/assets/ceeba53f-666d-472d-8188-ecebf33378e1)
我是新手 请教下好多 组件引入 之后报这个错误 使用uniapp vue 未使用语法糖

**Comment by sutras** [comment]
如何是通过HBuilderX创建的项目，出现这个问题的原因是sass版本过低，可以参考这个方法: #44
