### ISSUE TITLE
sar-datetime-picker-input type 问题

### ISSUE THREAD

**Issue by izrio** [sutras/sard-uniapp#51]
设置sar-datetime-picker-input  type="yMdh" 实际显示
<img width="243" alt="image" src="https://github.com/user-attachments/assets/6d76e641-1731-4ee7-b201-361b8ba9c05c">

**Comment by sutras** [comment]
输入框日期格式仅定义以下默认的映射：

```js
const mapTypeFormat = {
  y: 'YYYY',
  yM: 'YYYY-MM',
  yMd: 'YYYY-MM-DD',
  yMdhm: 'YYYY-MM-DD HH:mm',
  yMdhms: 'YYYY-MM-DD HH:mm:ss',
  hm: 'HH:mm',
  hms: 'HH:mm:ss',
}
```
如果要格式化为“年月日时”，可以使用“outlet-format”属性来定义想要的格式，例如：`outlet-format ="YYYY-MM-DD HH时"`。

更多使用方式，可以查看文档：
https://sutras.github.io/sard-uniapp-docs/#/components/datetime-picker-input
