### ISSUE TITLE
部分组件 突然都报错 了 

### ISSUE THREAD

**Issue by ab542273520** [sutras/sard-uniapp#52]
at ../node_modules/sard-uniapp/components/input/input.vue:1:0
16:59:59.255 16:59:59 [vite] [plugin:vite:import-analysis] ENOENT: no such file or directory, lstat 'D:\Kevin\Project\driver\node_modules\.pnpm\@dcloudio+uni-components@3.0.0-4020320240708001_postcss@8.4.39_rollup@4.18.1_vue@3.4.32_typescript@4.9.5_\node_modules\@dcloudio\uni-components\style\textarea.css'
16:59:59.255 at ../node_modules/sard-uniapp/components/input/input.vue:1:0

**Comment by sutras** [comment]
能否提供复现问题的最少代码？从仅有的提示信息不易找出问题原因。如果是“突然”报错，重启开发服务能否解决？
