### ISSUE TITLE
是否考虑支持抖音小程序

### ISSUE THREAD

**Issue by hzbnb** [sutras/sard-uniapp#53]
是否考虑支持抖音小程序

**Comment by sutras** [comment]
在微信小程序端已通过测试，抖音小程序没有测试过，但接口和组件都是通用的，应该不会有太大的兼容性问题。
如果使用过程中有什么问题，可以提issues或者PR。

**Comment by hzbnb** [comment]
你好， 抖音小程序我测试 button样式没问题  但是点击没反应  是的  click没反应  怀疑是emit整个都没反应 其他我还没有尝试

我目前的解决方案是把你的组件转化为setup语法糖的形式 重写一遍后正常  抖音小程序可能需要额外兼容

**Comment by sutras** [comment]
我研究了一下在uniapp下抖音小程序的开发过程，得到的结论是“sard-uniapp组件库不考虑兼容抖音小程序”。

主要原因有两个：
- 抖音小程序的组件如何设置了虚拟节点(virtualHost:true)，则监听不到发送的自定义事件；但如果不设置虚拟节点，因多了一个宿主元素，使得样式有很大的变动。设置虚拟节点能更接近Vue组件的表现，微信小程序、支付宝小程序都支持虚拟节点。
- 抖音小程序下依赖注入(provide、inject)函数不能使用。sard-uniapp很多组件都依赖这两个函数实现跨组件通信。

除了上面两个主要原因，还有以下其他的因素，例如：

- 抖音开发者工具中，事件修饰符 .stop.prevent 不能阻止页面滚动；
- 进入页面，样式加载会有所延迟，导致页面闪动（不知是uniapp还是抖音小程序问题）；
- 弹窗中的 picker 时而不能设置正确的位置。

除这些之外，网上还有一些零零碎碎的在uniapp下开发抖音小程序的问题。

**Comment by hzbnb** [comment]
这样嘛。好吧 谢谢大佬了
