### ISSUE TITLE
[sar-qrcode] H5不显示二维码

### ISSUE THREAD

**Issue by yukangyang** [sutras/sard-uniapp#55]
![image](https://github.com/user-attachments/assets/c710eb9c-17c5-41e1-aaa0-a92d5d5a42f3)
浏览器中不显示
![image](https://github.com/user-attachments/assets/ee129d31-b990-4d7f-a567-0554b85eb472)
小程序显示

**Comment by yukangyang** [comment]
```html
<sar-qrcode text="12212" color="#448475" />
```

**Comment by yukangyang** [comment]
![image](https://github.com/user-attachments/assets/e43b1908-16c1-4851-a12c-bf0856cff4c2)

**Comment by sutras** [comment]
我记忆中在某个版本的 uniapp 编译到 H5 后是会有不显示二维码的情况，后来换个版本的 uniapp 就可以正常显示了，你可以尝试一下。
你用的是哪个版本的 uniapp？把 package.json 中 @dcloudio/* 相关包的版本贴出来看一下？

**Comment by yukangyang** [comment]
4.29版本不显示，更新到最新4.36正常了
