### ISSUE TITLE
es6上传失败

### ISSUE THREAD

**Issue by hzbnb** [sutras/sard-uniapp#57]
微信小程序
不开启es6转es5 上传失败 开发版还是体验版都上传失败
![image](https://github.com/user-attachments/assets/69a3a328-42f2-4519-bfd5-5a8451389d2a)

开启es6转es5上传成功

**Comment by sutras** [comment]
在微信开发者工具中，勾选 "将 JS 编译成 ES5" 即可，可以兼容更多的设备，这增加不了多少代码体积，如果对代码体积敏感，则采用分包策略。
