### ISSUE TITLE
为什么我给组件设置样式不生效啊

### ISSUE THREAD

**Issue by chergn** [sutras/sard-uniapp#6]
![image](https://github.com/sutras/sard-uniapp/assets/43592730/4bb9e677-e16a-4cca-9b36-5d254d1c4503)
组件渲染出来的class确实是sar-rate啊

**Comment by sutras** [comment]
渲染出来的`sar-rate`是Rate组件内部定义的类名。
你在style中加了scoped，会让你编写的样式仅作用于当前的组件。
如果你要给Rate组件添加外边距，可以用一个view将其包裹，并将样式添加到这个view组件。
