### ISSUE TITLE
给组件class了，但没生效

### ISSUE THREAD

**Issue by chergn** [sutras/sard-uniapp#7]
![image](https://github.com/sutras/sard-uniapp/assets/43592730/8cd68671-f3ad-4a5f-bd5a-4118cfed3b47)

**Comment by sutras** [comment]
sard-uniapp所有的组件都设置了`virtualHost: true`，即自定义元素设置成了虚拟的，如果要将class或style这些外层属性合并到自定义组件内部第一层节点，可以使用`mergeVirtualHostAttributes`:
[https://uniapp.dcloud.net.cn/collocation/manifest.html#mp-weixin](https://uniapp.dcloud.net.cn/collocation/manifest.html#mp-weixin)

否则，你需要将sard-uniapp组件嵌套在一个view里面，并给这个view添加class和style。

**Comment by chergn** [comment]
可不可以开通 Discussions 模块啊？
![image](https://github.com/user-attachments/assets/1575eeec-8947-4a20-99fc-9d8584921224)

大家都在issues讨论不太合适吧
![image](https://github.com/user-attachments/assets/12000c53-6c4b-40ac-a843-7b3e7edf3997)
