### ISSUE TITLE
使用sar-popover组件报错

### ISSUE THREAD

**Issue by chergn** [sutras/sard-uniapp#9]
![image](https://github.com/sutras/sard-uniapp/assets/43592730/1c7f5329-604d-4efe-a114-0313f8c9ab8c)

**Comment by sutras** [comment]
sass 的 string.split() 方法需要Dart Sass 1.57.0版本之后才能使用，而HBuilderX安装的dart-sass版本为1.43.4，因此会报错。
建议使用sard-uniapp组件库的项目通过命令行的方式创建，而不是HBuilderX：
```bash
npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project
```
